/**
 * @author hexxone / https://hexx.one
 *
 * @license
 * Copyright (c) 2026 hexxone All rights reserved.
 * Licensed under the GNU GENERAL PUBLIC LICENSE.
 * See LICENSE file in the project root for full license information.
 *
 * @description
 * Wallaper Engine Basic Geometry worker.
 */

// Math lib is using 64bit precision float by default...
// so to not cast everything, use these short wrappers.

function isqrt(n: f32): f32 {
    return Math.sqrt(n) as f32;
}

function iabs(n: f32): f32 {
    return Math.abs(n) as f32;
}

function ilog(n: f32): f32 {
    return Math.log(n) as f32;
}

function ifloor(n: f64): i32 {
    return Math.floor(n) as i32;
}

function icos(n: f32): f32 {
    return Math.cos(n) as f32;
}

function isin(n: f32): f32 {
    return Math.sin(n) as f32;
}

/// ///////////////////////
//     Seeded Random
/// ///////////////////////

// seed used for this RNG
let seed: f32 = 1.0;

// generate seeded random float in Range[0,1]
// This is a Linear Congruential Generator (LCG) of the form:
// X_{n+1} = (a * X_n + c) % m
// where 'seed' is X_n, 'RNG_MULTIPLIER' is a, 'RNG_INCREMENT' is c, and 'RNG_MODULUS' is m.
// The result is then normalized to [0,1] by dividing by RNG_MODULUS.
const RNG_MULTIPLIER: f32 = 9301.0;
const RNG_INCREMENT: f32 = 49297.0;
const RNG_MODULUS: f32 = 233280.0;

function nextR(): f32 {
    seed = ((seed * RNG_MULTIPLIER + RNG_INCREMENT) % RNG_MODULUS) as f32;

    return (seed / RNG_MODULUS) as f32;
}

/// /////////////////////// ///
///     Fractal Geo         ///
/// /////////////////////// ///

// Constants for FractalGeometry algorithm
const DIMS: i32 = 3; // Number of dimensions (X, Y, Z)
const DEG_45_RAD: f32 = -0.785398; // -45 degrees in radians, used for rotation

// Initial point coordinate calculation factors
const INITIAL_X_Y_FACTOR_A: f32 = 100.0; // Denominator for s in x, y calculation
const INITIAL_X_Y_FACTOR_B: f32 = 0.5; // Offset for random component in x, y

// Thresholds for choosing different behaviors in the iteration
const ITERATION_CHOICE_THRESHOLD_1: f32 = 0.3; // Determines if points are generated by formula or copied
const ITERATION_Z_CHOICE_THRESHOLD_A: f32 = 0.5; // First threshold for z calculation variant
const ITERATION_Z_CHOICE_THRESHOLD_B: f32 = 0.75; // Second threshold for z calculation variant
const LOG_OFFSET_FOR_Z: f32 = 2.0; // Offset added in logarithmic z calculation

// Threshold for applying level spiralization
const LEVEL_SPIRALIZE_THRESHOLD: f32 = 0.5;

// Thresholds for point copying logic (second half of points)
const POINT_COPY_X_CHOICE_THRESHOLD: f32 = 0.1; // Determines if X is flipped or direct copied
const POINT_COPY_Y_CHOICE_THRESHOLD: f32 = 0.8; // Determines if Y is flipped or direct copied

// Normalization and scaling
const SCALE_NORMALIZATION_FACTOR: f32 = 2.0; // Factor used in scaling points (e.g. 2.0 * scaleFactor)

// Z-depth calculation for subsets
const SUBSET_Z_OFFSET_DIVISOR: f32 = 1024.0; // Divisor for calculating tmpSet (subset offset for noise)
const SUBSET_Z_INVERSION_FACTOR: f32 = 0.95; // Factor for inverting Z depth for alternate subsets

// Main settings, initialized in update()

// main Settings, these are updated by `update()` and used by `FractalGeometry`
// It's acceptable for these to be module-scoped as they represent shared configuration.
let numSubsets: i32; // Number of subsets per level
let numPoints: i32; // Number of points per subset
let hlfPoints: i32; // Half of numPoints, used for splitting point generation logic
let scaleFactor: f32; // Overall scaling factor for the geometry
let iRadius: f32; // Inner radius for tunnel processing (0-1 range from settings)
let oRadius: f32; // Outer radius for tunnel processing (0-1 range from settings)
let lDep: f32; // Level depth factor

// levelSpiral and levelCount are also set in update() and used in FractalGeometry
let levelSpiral: f32; // Spiralization factor for the current level (from settings)
let levelCount: i32; // Total number of levels (from settings)

/**
 * Generates fractal geometry for a given level.
 * The geometry is composed of several "subsets" of points.
 * The generation involves iterative formulas, random choices, and scaling.
 * @param {i32} levelId The ID of the level to generate.
 * @returns {Array<Float32Array | null> | null} An array of Float32Arrays, where each Float32Array contains the XYZ
 *          coordinates for a subset of points. Returns null if initial data (lastData) is not set up.
 */
function FractalGeometry(levelId: i32): Array<Float32Array | null> | null {
    if (lastData === null) {
        // Ensure lastData is initialized, typically by calling update() first.
        return null;
    }

    // Local variables for FractalGeometry function
    let maxX: f32; let minX: f32; let current_x: f32; let newX: f32;
    let maxY: f32; let minY: f32; let current_y: f32; let newY: f32;
    let s: i32; let idx: i32;
    let bid: i32; let current_z: f32; let x1: f32;
    let dist: f32; let outer: f32; let scaling: f32;
    let lData: Float32Array; // Initialized inside the loop
    let tmpSet: f32;

    // Initialize algorithm parameters (al, bl, cl, dl, el) with randomized values.
    // These parameters are derived from ranges specified in levelSettings (indices 6-15).
    // The formula is: param = min_val + random[0-1] * (max_val - min_val)
    // These are effectively local to FractalGeometry as they are recalculated each time.
    const al = levelSettings[6] + nextR() * (levelSettings[7] - levelSettings[6]);
    const bl = levelSettings[8] + nextR() * (levelSettings[9] - levelSettings[8]);
    const cl = levelSettings[10] + nextR() * (levelSettings[11] - levelSettings[10]);
    const dl = levelSettings[12] + nextR() * (levelSettings[13] - levelSettings[12]);
    const el = levelSettings[14] + nextR() * (levelSettings[15] - levelSettings[14]);

    // Generate two random choices (choice1, choice2) for this level's generation process.
    // These influence various conditional paths in the algorithm.
    // Effectively local as they are recalculated each time.
    const choice1 = nextR();
    const choice2 = nextR();

    // Reset min/max coordinate trackers for this level.
    maxX = maxY = minX = minY = 0;

    // Loop through each subset that makes up the current level's geometry.
    for (s = 0; s < numSubsets; s++) {
        // Initialize starting (x, y) coordinates for the current subset.
        // These are slightly varied per subset using the subset index 's' and a random factor.
        current_x = (((s as f32) / INITIAL_X_Y_FACTOR_A) * (INITIAL_X_Y_FACTOR_B - nextR())) as f32;
        current_y = (((s as f32) / INITIAL_X_Y_FACTOR_A) * (INITIAL_X_Y_FACTOR_B - nextR())) as f32;

        // Get the Float32Array for the current subset's point data.
        const currentLData = lastData![s]; // Use a new local var to hold data for this iteration

        if (currentLData === null) {
            // Should not happen if update() was called correctly.
            continue;
        }
        lData = currentLData;


        // This line seems to be a commented-out alternative way to calculate a per-subset value.
        // tmp = (choice1 + ((choice2 - choice1) * ((s / numSubsets) as f32)));

        // Loop through each point in the current subset.
        for (idx = 0; idx < numPoints; idx++) {
            // Generate points:
            // The first half of points (or more, depending on choice1) are generated using an iterative formula.
            // The second half is typically copied/transformed from the first half.
            if (idx < hlfPoints || choice1 > ITERATION_CHOICE_THRESHOLD_1) {
                // Iteration formula part (generalization of a formula by Barry Martin).
                // The exact formula for 'current_z' depends on 'choice1'.
                if (choice1 < ITERATION_Z_CHOICE_THRESHOLD_A) {
                    current_z = dl + isqrt(iabs(bl * current_x - cl));
                } else if (choice1 < ITERATION_Z_CHOICE_THRESHOLD_B) {
                    // Using square root of square root (quartic root)
                    current_z = dl + isqrt(isqrt(iabs(bl * current_x - cl)));
                } else {
                    // Using logarithm
                    current_z = dl + ilog(LOG_OFFSET_FOR_Z + isqrt(iabs(bl * current_x - cl)));
                }

                // Update x1 based on current_y and current_z, conditioned by the sign of current_x.
                if (current_x > 0) {
                    x1 = current_y - current_z;
                } else if (current_x === 0) {
                    x1 = current_y; // If current_x is zero, x1 is just current_y.
                } else {
                    x1 = current_y + current_z;
                }

                // Update current_y and current_x for the next iteration or final point.
                current_y = al - current_x;
                current_x = x1 + el;

                // Rotate the generated point (current_x, current_y).
                // The rotation angle depends on levelSpiral, levelId, subset index 's', and total levelCount.
                const rotated = rotatePoint( // capture result from rotatePoint
                    current_x,
                    current_y,
                    levelSpiral > LEVEL_SPIRALIZE_THRESHOLD
                        ? (-(levelId as f32) * DEG_45_RAD + ((s as f32) * DEG_45_RAD) / (levelCount as f32))
                        : DEG_45_RAD
                );

                // Store rotated coordinates.
                newX = rotated.x; // Use returned object
                newY = rotated.y; // Use returned object
            } else {
                // Point copying part (for the second half of points, if choice1 <= ITERATION_CHOICE_THRESHOLD_1).
                // Points are copied from the first half (idx - hlfPoints).
                // X and Y coordinates might be flipped based on choice1 and choice2.
                if (choice1 > POINT_COPY_X_CHOICE_THRESHOLD) {
                    newX = -lData[(idx - hlfPoints) * DIMS]; // Flipped X
                } else {
                    newX = lData[(idx - hlfPoints) * DIMS]; // Direct copy X
                }
                if (choice2 > POINT_COPY_Y_CHOICE_THRESHOLD) {
                    newY = -lData[(idx - hlfPoints) * DIMS + 1]; // Flipped Y
                } else {
                    newY = lData[(idx - hlfPoints) * DIMS + 1]; // Direct copy Y
                }
            }

            // Update min/max X and Y coordinates for the current level based on the new point.
            if (newX < minX) {
                minX = newX;
            } else if (newX > maxX) {
                maxX = newX;
            }
            if (newY < minY) {
                minY = newY;
            } else if (newY > maxY) {
                maxY = newY;
            }

            // Store the generated/copied (newX, newY) into the current subset's data array.
            bid = idx * DIMS; // Calculate buffer index for X coordinate.
            lData[bid] = newX;
            lData[bid + 1] = newY;
            // Z coordinate is calculated later, after scaling X and Y.
        }
    }

    // After generating all points for all subsets, calculate scaling factors.
    // This normalizes the geometry to fit within a range defined by scaleFactor.
    const scaleX = (SCALE_NORMALIZATION_FACTOR * scaleFactor) / (maxX - minX);
    const scaleY = (SCALE_NORMALIZATION_FACTOR * scaleFactor) / (maxY - minY);

    // Calculate scaled level depth for Z coordinates. levelSettings[1] is numSubsetsPerLevel from WE.
    // This seems to intend to use the 'numSubsetsPerLevel' setting from Wallpaper Engine,
    // which might be different from the 'numSubsets' (derived from levelSettings[1]) used in loops.
    // Assuming levelSettings[1] correctly represents the intended divisor for depth scaling here.
    const ldnum = lDep / levelSettings[1]; // levelSettings[1] should be num_subsets_per_level

    // Normalize coordinates and apply post-processing effects (tunnel, Z-depth noise).
    for (s = 0; s < numSubsets; s++) {
        if (lastData![s] === null) {
            continue;
        }
        lData = lastData![s]!;

        // Calculate tmpSet: an offset based on level and subset ID, used for noise variation.
        tmpSet = ((levelId * numSubsets + s) as f32) / SUBSET_Z_OFFSET_DIVISOR;

        for (idx = 0; idx < numPoints; idx++) {
            bid = idx * DIMS; // Buffer index for X.

            // Retrieve unscaled X and Y.
            let point_x = lData[bid]; // Use new local variables for clarity
            let point_y = lData[bid + 1];

            // Apply scaling and recentering.
            // Points are scaled based on the calculated range (maxX-minX, maxY-minY)
            // and then shifted so the geometry is centered around (0,0).
            point_x = scaleX * (point_x - minX) - scaleFactor;
            point_y = scaleY * (point_y - minY) - scaleFactor;

            // Tunnel processing:
            // If iRadius > 0, points close to the center are pushed outwards.
            if (iRadius > 0) {
                dist = getPointDistance(0, 0, point_x, point_y) / scaleFactor; // Normalized distance from center.
                if (dist < iRadius) {
                    // If point is within inner radius, calculate scaling to push it out.
                    scaling = dist / iRadius; // How far inside the inner radius the point is.
                    outer = scaling / oRadius; // Further scaling based on outer radius.
                    // Apply the push-out transformation.
                    point_x = point_x / scaling + point_x * outer;
                    point_y = point_y / scaling + point_y * outer;
                }
            }
            // Store the final scaled and processed X and Y values.
            lData[bid] = point_x;
            lData[bid + 1] = point_y;

            // Calculate Z coordinate using a noise function.
            // The noise function `makeNoise` uses the final X, Y, tmpSet, and scaleFactor.
            // The result is then multiplied by the scaled level depth `ldnum`.
            if (DIMS === 3) { // Only if DIMS is 3 (i.e., we need Z coordinates).
                lData[bid + 2] = makeNoise(point_x, point_y, tmpSet, scaleFactor, choice1, choice2) * ldnum;
                // Invert Z for every second subset to create variation.
                if (s % 2 === 1) {
                    lData[bid + 2] = ldnum - lData[bid + 2] * SUBSET_Z_INVERSION_FACTOR;
                }
            }
        }
    }

    // Return the populated and processed point data for the level.
    return lastData;
}

/// ///////////////////////
//       Utilities
/// ///////////////////////

function getPointDistance(x1: f32, y1: f32, x2: f32, y2: f32): f32 {
    const a_dist: f32 = x1 - x2; // Difference in x coordinates
    const b_dist: f32 = y1 - y2; // Difference in y coordinates

    // Pythagorean theorem: sqrt(a^2 + b^2)
    return isqrt(a_dist * a_dist + b_dist * b_dist);
}

// TODO implement variable size for each point
// let closestDist: f32; let closestIndx: i32; let oX: f32; let oY: f32; let pDist: f32;
// function closestIndex(arr: Float32Array, pIndx: i32): i32 {
//     oX = arr[pIndx];
//     oY = arr[pIndx + 1];
//     closestDist = 100000;
//     closestIndx = -1;
//     for (let pos = 0; pos < arr.length; pos += DIMS) {
//         // skip own point, cause its obviously 0 distance
//         if (pos === pIndx) { continue; }
//         // calculate point distance
//         pDist = getPointDistance(oX, oY, arr[pos], arr[pos + 1]);
//         if (pDist < closestDist) {
//             closestDist = pDist;
//             closestIndx = pos;
//         }
//     }
//     return closestIndx;
// }

// Class or object to return two values from rotatePoint
class Point {

    constructor(public x: f32, public y: f32) {}

}

// assumes the point is already relative to center
function rotatePoint(pX: f32, pY: f32, angle: f32): Point {
    const tmpCos: f32 = Math.cos(angle) as f32; // Cache cosine of angle
    const tmpSin: f32 = Math.sin(angle) as f32; // Cache sine of angle
    // Standard 2D rotation formulas:
    // x' = x*cos(theta) - y*sin(theta)
    // y' = y*cos(theta) + x*sin(theta)
    const rotX: f32 = pX * tmpCos - pY * tmpSin;
    const rotY: f32 = pY * tmpCos + pX * tmpSin;

    return new Point(rotX, rotY);
}

/// ///////////////////////
//     Depth Noise
/// ///////////////////////

// Constants for noise generation
const NOISE_STX_BASE: f32 = -30.0;
const NOISE_STX_OFFS_MULTIPLIER: f32 = 240.0;
const NOISE_STX_SCALE_MULTIPLIER_A: f32 = 1.0;
const NOISE_STX_SCALE_MULTIPLIER_B: f32 = 6.0;

const NOISE_STY_BASE: f32 = -20.0;
const NOISE_STY_OFFS_MULTIPLIER: f32 = 320.0;
const NOISE_STY_SCALE_MULTIPLIER_A: f32 = 1.0;
const NOISE_STY_SCALE_MULTIPLIER_B: f32 = 5.0;

// Thresholds for conditional mixing and function choice in noise generation
const NOISE_TRIG_CHOICE_THRESHOLD: f32 = 0.4; // Determines using cos or sin initially
const NOISE_MIX_CHOICE_THRESHOLD_1: f32 = 0.8; // Determines if first mix occurs
const NOISE_MIX_TRIG_CHOICE_THRESHOLD: f32 = 0.5; // Determines cos/sin for mixed components
const NOISE_MIX_CHOICE_THRESHOLD_2: f32 = 0.7; // Determines if second mix occurs

/**
 * Mixes two values 'a' and 'b' based on an interpolator 'i'.
 * The fractional part of 'i' is used for linear interpolation.
 * @param {f32} a First value.
 * @param {f32} b Second value.
 * @param {f32} interpolator Interpolation factor.
 * @returns {f32} The mixed value.
 */
function mix(a: f32, b: f32, interpolator: f32): f32 { // Renamed i to interpolator
    return a + (b - a) * (interpolator % 1.0); // Using (interpolator % 1.0) ensures interpolator is in [0,1)
}

/**
 * Helper function for makeNoise. Generates a component of the noise.
 * It transforms input coordinates (stx, sty) based on offset (offS),
 * scale, and global random choices (choice1, choice2).
 * @param {f32} stx Input X coordinate.
 * @param {f32} sty Input Y coordinate.
 * @param {f32} offS Offset, typically derived from subset index.
 * @param {f32} scale Overall scale factor.
 * @param {f32} choice1_param Random choice parameter 1.
 * @param {f32} choice2_param Random choice parameter 2.
 * @returns {f32} A noise component value.
 */
function helpNoise(stx: f32, sty: f32, offS: f32, scale: f32, choice1_param: f32, choice2_param: f32): f32 {
    // Transform stx and sty based on input parameters and passed random choices
    // These transformations create a complex, somewhat chaotic input for the noise.
    stx = NOISE_STX_BASE + NOISE_STX_OFFS_MULTIPLIER * offS * choice1_param
        + (iabs(stx) / scale) * (NOISE_STX_SCALE_MULTIPLIER_A + NOISE_STX_SCALE_MULTIPLIER_B * choice2_param);
    sty = NOISE_STY_BASE + NOISE_STY_OFFS_MULTIPLIER * offS * choice2_param
        + (iabs(sty) / scale) * (NOISE_STY_SCALE_MULTIPLIER_A + NOISE_STY_SCALE_MULTIPLIER_B * choice1_param);

    // Return the magnitude of the transformed (stx, sty) vector.
    return isqrt(stx * stx + sty * sty);
}

/**
 * Generates a noise value based on input coordinates (stx, sty), an offset (offS), and scale.
 * This noise is used for Z-depth calculation. It involves multiple calls to helpNoise
 * and mixes their results using trigonometric functions and linear interpolation,
 * influenced by global random choices (choice1, choice2).
 * @param {f32} stx Input X coordinate.
 * @param {f32} sty Input Y coordinate.
 * @param {f32} offS Offset, typically derived from subset index.
 * @param {f32} scale Overall scale factor.
 * @param {f32} choice1_param Random choice parameter 1, passed from FractalGeometry.
 * @param {f32} choice2_param Random choice parameter 2, passed from FractalGeometry.
 * @returns {f32} The final noise value.
 */
function makeNoise(stx: f32, sty: f32, offS: f32, scale: f32, choice1_param: f32, choice2_param: f32): f32 {
    let noitmp: f32; // Temporary noise value, now local
    let noires: f32; // Resulting noise value, now local

    // Initial noise calculation
    noitmp = helpNoise(stx, sty, offS, scale, choice1_param, choice2_param);
    // Apply cosine or sine based on choice1_param
    noitmp = choice1_param < NOISE_TRIG_CHOICE_THRESHOLD ? icos(noitmp) : isin(noitmp);
    noires = noitmp; // Store as the current result

    // First conditional mix
    if (choice1_param < NOISE_MIX_CHOICE_THRESHOLD_1) {
        noitmp = helpNoise(stx, sty, offS, scale, choice1_param, choice2_param);
        // Apply cosine or sine based on choice1_param (using a different threshold pattern here)
        noitmp = choice1_param < NOISE_MIX_TRIG_CHOICE_THRESHOLD ? icos(noitmp) : isin(noitmp);
        noires = mix(noires, noitmp, choice1_param); // Mix current result with new temporary noise
    }

    // Second conditional mix, using choice2_param
    if (choice2_param < NOISE_MIX_CHOICE_THRESHOLD_2) {
        noitmp = helpNoise(stx, sty, offS, scale, choice1_param, choice2_param);
        // Apply cosine or sine based on choice2_param
        noitmp = choice2_param < NOISE_MIX_TRIG_CHOICE_THRESHOLD ? icos(noitmp) : isin(noitmp);
        noires = mix(noires, noitmp, choice2_param); // Mix current result with new temporary noise
    }

    return noires; // Return the final accumulated or mixed noise value
}

/// ///////////////////////
//     Main Program
/// ///////////////////////

// this will hold the current processing settings
export const levelSettings = new Float32Array(20);
levelSettings.fill(0.0);

// this will hold the last allocated array for re-use
let lastData: Array<Float32Array | null> | null = null;

// Call after updating settings always
// noinspection JSUnusedGlobalSymbols
export function update(): void {
    numSubsets = ifloor(levelSettings[1]);
    numPoints = ifloor(levelSettings[2]);
    hlfPoints = ifloor(numPoints / 2);
    scaleFactor = levelSettings[3];
    iRadius = levelSettings[4] / 100;
    oRadius = levelSettings[5] / 100;
    seed = levelSettings[16];
    lDep = levelSettings[17];
    levelSpiral = levelSettings[18];
    levelCount = ifloor(levelSettings[19]);

    // create a buffer thats big enough to hold the x & y corrdinates of all points in a subset.
    // may seem ridiclous, but is actually the best way to transfer the data back
    // also, if the array did not change in size, don't recreate it every time...

    lastData = new Array<Float32Array | null>(numSubsets);
    if (lastData !== null) {
        for (let s = 0; s < numSubsets; s++) {
            lastData![s]! = new Float32Array(numPoints * DIMS);
        }
    }
}

// Build and return a level by specified settings
// noinspection JSUnusedGlobalSymbols
export function build(id: i32): Array<Float32Array | null> | null {
    // run generator
    return FractalGeometry(id);
}

// noinspection JSUnusedGlobalSymbols
export const Copyright_by_hexxone: bool = true;
